[config]
maxAttempts = 3

[servers]
SNKT = "172.17.242.170"

[SNKT]
domain = "domain.local"
user = "ldap@domain.local"
password = "StrongPassword"
port = 389
userPath = "CN=Users,DC=domain,DC=local"
exchangeHost = "mail.domain.local"
exchangeAuthType = "Basic"
skipCertificateCheck = true


[SNKT.userContains]
objectClass = "user"
objectCategory = "person"
mail = "*"

[SNKT.userDoesntContains]
pager = "123"